from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, Tuple
from matplotlib import font_manager

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.RAW_LSTM.config import Settings
from src.RAW_LSTM.data import WindowDataset, feature_matrix
from src.RAW_LSTM.model import LSTMForecaster


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate an LSTM checkpoint and plot predictions.")
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=PROJECT_ROOT / "models" / "checkpoints" / "lstm_all.pt",
        help="Path to the trained checkpoint.",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=PROJECT_ROOT / "data" / "processed" / "meteorology.csv",
        help="Processed CSV generated by scripts/prepare_data.py.",
    )
    parser.add_argument("--station", type=str, default=None, help="Optional station filter (must exist in the CSV).")
    parser.add_argument("--batch-size", type=int, default=256, help="Batch size for evaluation.")
    parser.add_argument(
        "--plot",
        type=Path,
        default=PROJECT_ROOT / "plots" / "lstm_predictions.png",
        help="Where to store the prediction vs. actual plot.",
    )
    parser.add_argument("--device", type=str, default=None, help="Force cpu/cuda choice.")
    parser.add_argument(
        "--max-points",
        type=int,
        default=None,
        help="Optionally limit the number of points shown in the plot for readability.",
    )
    parser.add_argument(
        "--font",
        type=str,
        default="DejaVu Sans",
        help="Matplotlib font family name used for axes labels/title.",
    )
    parser.add_argument(
        "--font-file",
        type=Path,
        default=None,
        help="Optional path to a .ttf/.otf font file containing Chinese characters.",
    )
    return parser.parse_args()


def load_checkpoint(checkpoint_path: Path, device: torch.device) -> Tuple[dict, Dict[str, torch.Tensor]]:
    payload = torch.load(checkpoint_path, map_location=device, weights_only=False)
    if "model_state" not in payload:
        raise KeyError("Checkpoint missing 'model_state'.")
    return payload, payload["model_state"]


def prepare_dataframe(csv_path: Path, station: str | None) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"Processed CSV not found: {csv_path}")
    df = pd.read_csv(csv_path, parse_dates=["timestamp"])
    if station:
        df = df[df["station"] == station]
    if df.empty:
        raise ValueError("No rows found for the requested configuration/station.")
    df = df.sort_values("timestamp")
    return df


def infer_device(arg_device: str | None) -> torch.device:
    if arg_device:
        return torch.device(arg_device)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def main() -> None:
    args = parse_args()
    device = infer_device(args.device)
    settings = Settings()

    if args.font_file:
        if not args.font_file.exists():
            raise FileNotFoundError(f"Font file not found: {args.font_file}")
        font_manager.fontManager.addfont(str(args.font_file))
        font_prop = font_manager.FontProperties(fname=str(args.font_file))
        plt.rcParams["font.family"] = font_prop.get_name()
    else:
        plt.rcParams["font.family"] = args.font

    payload, model_state = load_checkpoint(args.checkpoint, device)
    feature_cols = payload["feature_cols"]
    target_col = payload["target_col"]
    normalization = payload["normalization"]

    saved_settings = payload.get("settings", {})
    data_cfg = saved_settings.get("data", {})
    training_cfg = saved_settings.get("training", {})

    input_window = training_cfg.get("input_window", settings.training.input_window)
    horizon = training_cfg.get("forecast_horizon", settings.training.forecast_horizon)
    train_ratio = data_cfg.get("train_ratio", settings.data.train_ratio)

    df = prepare_dataframe(args.data, args.station)

    missing = [col for col in feature_cols if col not in df.columns]
    if missing:
        raise ValueError(f"Missing columns required by the checkpoint: {missing}")

    matrix = feature_matrix(df, feature_cols)
    mean = np.asarray(normalization["mean"], dtype=np.float32)
    std = np.asarray(normalization["std"], dtype=np.float32)
    std[std == 0] = 1.0
    matrix = (matrix - mean) / std

    min_required = input_window + horizon
    if len(matrix) < min_required * 2:
        raise ValueError("Not enough samples available for evaluation with the stored hyper-parameters.")

    split_idx = int(len(matrix) * train_ratio)
    split_idx = max(split_idx, min_required)
    split_idx = min(split_idx, len(matrix) - min_required)

    target_idx = feature_cols.index(target_col)
    eval_dataset = WindowDataset(
        matrix,
        target_idx=target_idx,
        window_size=input_window,
        horizon=horizon,
        start=split_idx,
    )
    if len(eval_dataset) == 0:
        raise ValueError("Evaluation dataset is empty. Check the split ratio or dataset size.")

    eval_loader = DataLoader(eval_dataset, batch_size=args.batch_size, shuffle=False)

    model = LSTMForecaster(
        input_size=len(feature_cols),
        hidden_size=training_cfg.get("hidden_size", settings.training.hidden_size),
        horizon=horizon,
        num_layers=training_cfg.get("num_layers", settings.training.num_layers),
        dropout=training_cfg.get("dropout", settings.training.dropout),
    ).to(device)
    model.load_state_dict(model_state)

    model.eval()
    preds_list: list[torch.Tensor] = []
    targets_list: list[torch.Tensor] = []
    with torch.no_grad():
        for features, targets in eval_loader:
            preds = model(features.to(device))
            preds_list.append(preds.cpu())
            targets_list.append(targets)

    preds = torch.cat(preds_list).numpy()
    targets = torch.cat(targets_list).numpy()

    target_mean = mean[target_idx]
    target_std = std[target_idx]
    preds = preds * target_std + target_mean
    targets = targets * target_std + target_mean

    diff = preds - targets
    mse = float(np.mean(diff**2))
    rmse = float(np.sqrt(mse))
    mae = float(np.mean(np.abs(diff)))
    print(f"Validation RMSE: {rmse:.4f}")
    print(f"Validation MAE : {mae:.4f}")

    timestamps = df["timestamp"].to_numpy()
    start_time_idx = split_idx + input_window
    indices = start_time_idx + np.arange(len(preds))
    indices = np.clip(indices, 0, len(timestamps) - 1)
    time_axis = timestamps[indices]

    values_to_plot = slice(None)
    if args.max_points is not None and args.max_points > 0:
        values_to_plot = slice(-args.max_points, None)
        print(f"Plotting the last {args.max_points} predictions for readability.")

    output_dir = args.plot.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(12, 5))
    plt.plot(time_axis[values_to_plot], targets[:, 0][values_to_plot], label="Actual", linewidth=2)
    plt.plot(time_axis[values_to_plot], preds[:, 0][values_to_plot], label="Predicted", linewidth=2)
    plt.title(f"LSTM forecast - horizon {horizon} (showing first step)")
    plt.xlabel("Timestamp")
    plt.ylabel(target_col)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.plot)
    plt.close()
    print(f"Saved plot to {args.plot}")


if __name__ == "__main__":
    main()
