function mdl = create_pdppo_demo_model()
%CREATE_PDPO_DEMO_MODEL Build a minimal Simulink model for the demo.

rootDir = fileparts(fileparts(mfilename("fullpath")));
mdl = "pdppo_scheduler_demo";
modelFile = fullfile(rootDir, mdl + ".slx");

if bdIsLoaded(mdl)
    close_system(mdl, 0);
end

new_system(mdl);
load_system("simulink");

set_param(mdl, "StopTime", "239");
set_param(mdl, "Solver", "FixedStepDiscrete");
set_param(mdl, "FixedStep", "1");

add_block("simulink/Sources/From Workspace", mdl + "/Demo Observation", ...
    "VariableName", "pdppo_demo_obs", ...
    "Position", [70 95 195 135]);

add_block("simulink/User-Defined Functions/Interpreted MATLAB Fcn", ...
    mdl + "/Frozen PD-PPO Scheduler", ...
    "MATLABFcn", "pdppo_demo_step", ...
    "OutputDimensions", "[1 8]", ...
    "Position", [260 88 445 142]);

add_block("simulink/Signal Routing/Mux", mdl + "/Obs Mask Mux", ...
    "Inputs", "2", ...
    "Position", [520 145 550 210]);

add_block("simulink/User-Defined Functions/Interpreted MATLAB Fcn", ...
    mdl + "/Apply Channel Mask", ...
    "MATLABFcn", "pdppo_apply_mask", ...
    "OutputDimensions", "[1 8]", ...
    "Position", [600 155 760 205]);

add_block("simulink/Sinks/To Workspace", mdl + "/Partial Observation", ...
    "VariableName", "pdppo_partial_out", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [830 155 970 205]);

add_block("simulink/Sinks/To Workspace", mdl + "/Scheduled Mask", ...
    "VariableName", "pdppo_mask_out", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [830 80 970 130]);

add_block("simulink/Sinks/Scope", mdl + "/Mask Scope", ...
    "Position", [830 235 970 295]);

add_line(mdl, "Demo Observation/1", "Frozen PD-PPO Scheduler/1", "autorouting", "on");
add_line(mdl, "Frozen PD-PPO Scheduler/1", "Scheduled Mask/1", "autorouting", "on");
add_line(mdl, "Frozen PD-PPO Scheduler/1", "Mask Scope/1", "autorouting", "on");
add_line(mdl, "Demo Observation/1", "Obs Mask Mux/1", "autorouting", "on");
add_line(mdl, "Frozen PD-PPO Scheduler/1", "Obs Mask Mux/2", "autorouting", "on");
add_line(mdl, "Obs Mask Mux/1", "Apply Channel Mask/1", "autorouting", "on");
add_line(mdl, "Apply Channel Mask/1", "Partial Observation/1", "autorouting", "on");

annotation = sprintf(["Frozen PD-PPO scheduler demo\\n", ...
    "Input: 17-D observation vector\\n", ...
    "Output: 8-D executable channel mask and partial observations"]);
Simulink.Annotation(mdl, annotation, "Position", [70 20 360 70]);

save_system(mdl, modelFile);
end
